#!/usr/bin/env node
const fs=require('fs');const path=require('path');const os=require('os');
class LearningLoop{
  constructor(o={}){this.cd=o.configDir||path.join(os.homedir(),'.workbuddy','learning-loop');this.sessions=[];this.instincts=new Map();this.feedbackLoop={cycle:0,totalLearned:0,lastRun:null};this.Phase={OBSERVE:'observe',EXTRACT:'extract',VALIDATE:'validate',APPLY:'apply',REFINE:'refine'};this.Confidence={HIGH:80,MEDIUM:60,LOW:40,EXPERIMENTAL:20};['sessions','instincts','feedback'].forEach(d=>{const p=path.join(this.cd,d);if(!fs.existsSync(p))fs.mkdirSync(p,{recursive:true});});}
  _id(){return Math.random().toString(36).substring(2,10);}
  _ts(){return new Date().toISOString();}
  analyzeSession(d){const a={sessionId:d.id||this._id(),timestamp:this._ts(),taskType:d.taskType||'unknown',complexity:d.complexity||5,duration:d.duration||0,toolCalls:d.toolCalls||0,success:d.success!==false,errorCount:d.errors||0,patterns:[],extractedInstincts:[],recommendations:[]};if(d.toolCalls>10&&d.success)a.patterns.push({type:'high_tool_usage_success',confidence:70});if(d.errorCount===0&&d.complexity>5)a.patterns.push({type:'complex_task_flawless',confidence:85});if(d.toolCalls>3&&d.toolCalls<8&&d.success)a.patterns.push({type:'efficient_execution',confidence:75});this.sessions.push(a);if(this.sessions.length>100)this.sessions=this.sessions.slice(-100);return a;}
  extractInstincts(a){const e=[];for(const p of a.patterns){if(p.confidence>=this.Confidence.HIGH){const exist=[...this.instincts.values()].find(i=>i.type===p.type);if(exist){exist.confidence=Math.min(100,exist.confidence+5);exist.occurrences++;exist.lastSeen=this._ts();}else{const ni={id:'inst_'+this._id(),type:p.type,confidence:p.confidence,source:'session_pattern',occurrences:1,firstSeen:this._ts(),lastSeen:this._ts(),taskType:a.taskType,status:'active'};this.instincts.set(ni.id,ni);e.push({action:'created',instinct:ni});}}}a.extractedInstincts=e;return e;}
  recordFeedback(f){const fb={id:this._id(),sessionId:f.sessionId,taskType:f.taskType||'unknown',model:f.model||'unknown',reward:f.reward||0,timestamp:this._ts()};this.feedbackLoop.cycle++;this.feedbackLoop.totalLearned++;for(const[id,ins]of this.instincts){if(ins.taskType===fb.taskType&&ins.status==='active'){if(fb.reward>0)ins.confidence=Math.min(100,ins.confidence+fb.reward*2);else{ins.confidence=Math.max(10,ins.confidence-Math.abs(fb.reward)*3);if(ins.confidence<20)ins.status='deprecated';}}}return fb;}
  runLearningCycle(d){this.feedbackLoop.lastRun=this._ts();const a=this.analyzeSession(d);const ins=this.extractInstincts(a);return{cycle:this.feedbackLoop.cycle,analysis:a,instinctsExtracted:ins.length,instincts:ins,totalInstincts:this.instincts.size,recommendations:[]};}
  getInstincts(f={}){let r=[...this.instincts.values()];if(f.taskType)r=r.filter(i=>i.taskType===f.taskType);if(f.minConfidence)r=r.filter(i=>i.confidence>=f.minConfidence);if(f.status)r=r.filter(i=>i.status===f.status);return r.sort((a,b)=>b.confidence-a.confidence);}
  getTopInstincts(n=5){return this.getInstincts({status:'active'}).slice(0,n);}
  getLoopStats(){const all=[...this.instincts.values()];return{cycles:this.feedbackLoop.cycle,totalLearned:this.feedbackLoop.totalLearned,lastRun:this.feedbackLoop.lastRun,activeInstincts:all.filter(i=>i.status==='active').length,deprecatedInstincts:all.filter(i=>i.status==='deprecated').length,sessions:this.sessions.length,avgConfidence:all.length>0?Math.round(all.reduce((s,i)=>s+i.confidence,0)/all.length):0};}
  reset(){this.sessions=[];this.instincts.clear();this.feedbackLoop={cycle:0,totalLearned:0,lastRun:null};return{reset:true};}
}
if(require.main===module){const ll=new LearningLoop();const cmd=process.argv[2];const a=process.argv;const get=(k,d)=>{const i=a.indexOf(k);return i>-1?a[i+1]:d;};switch(cmd){case'cycle':{const r=ll.runLearningCycle({id:get('--session','s1'),taskType:get('--type','general'),complexity:parseInt(get('--complexity','5')),toolCalls:parseInt(get('--toolcalls','5')),success:!a.includes('--fail'),duration:100});console.log('Cycle '+r.cycle+': '+r.instinctsExtracted+' instincts');break;}case'feedback':{const r=ll.recordFeedback({sessionId:get('--session','s1'),taskType:get('--type','general'),reward:parseInt(get('--reward','5'))});console.log('Feedback: reward='+r.reward);break;}case'instincts':{const f={};if(a.includes('--type'))f.taskType=get('--type');if(a.includes('--min'))f.minConfidence=parseInt(get('--min'));ll.getInstincts(f).forEach(i=>console.log(' ['+i.confidence+'%] '+i.type));break;}case'top':ll.getTopInstincts(parseInt(a[1])||5).forEach((i,n)=>console.log(' #'+(n+1)+' ['+i.confidence+'%] '+i.type));break;case'stats':console.log(JSON.stringify(ll.getLoopStats(),null,2));break;case'reset':ll.reset();console.log('Reset');break;default:console.log('LearningLoop: cycle feedback instincts top stats reset help');}}
module.exports=LearningLoop;
console.log('[LearningLoop] OK - P4-8');
